Sandstorm:
  ContentWorkflow:
    workflows:
      'tech_blog_post':
        name: 'Tech Blog Post'
        description: 'Create a technical blog post (possibly deep dive)'
        initialStep: idea
        steps:
          idea:
            name: 'Idea'
            description: 'Jot down the rough idea of the blog post (Bullet points, markdown is fine)'
            backendFusionComponent: 'Sandstorm.ContentWorkflow:Step.MarkdownfieldInput'
#          outline:
#            name: 'Post Outline'
#            description: ''
#          draft:
#            name: 'Write draft'
#            description: ''
#          review:
#            name: 'Review and improve draft'
#            description: ''
#          published:
#            name: 'Published'
#            description: ''
#          sharedOnSocialMedia:
#            name: 'Shared on social media'
#            description: ''
