Neos:
  Neos:
    modules:
      management:
        submodules:
          contentWorkflow:
            label: 'Content Workflow'
            description: 'Content Workflows'
            icon: 'magic'
            controller: 'Sandstorm\ContentWorkflow\Controller\BackendModuleController'
            privilegeTarget: 'Sandstorm.ContentWorkflow:BackendModuleController'
            additionalResources:
              styleSheets:
                - 'resource://Wwwision.Neos.ModuleComponents/Public/Styles/module.css'
                - 'resource://Sandstorm.ContentWorkflow/Public/built/BackendModule.css'
              javaScripts:
                - 'resource://Wwwision.Neos.ModuleComponents/Public/Scripts/module.js'
                - 'resource://Sandstorm.ContentWorkflow/Public/built/BackendModule.js'

    Ui:
      frontendConfiguration:
        'Sandstorm.ContentWorkflow':
          'definedWorkflows': '${Neos.Ui.PositionalArraySorter.sort(Configuration.setting(''Sandstorm.ContentWorkflow.workflows''))}'
      resources:
        javascript:
          'Sandstorm.ContentWorkflow':
            resource: 'resource://Sandstorm.ContentWorkflow/Public/built/ContentModule.js'
            # esm support²
            # in case you want to use esbuild's code splitting (ESM only)
            # or just reference an ESM Plugin, set the type to module
            # attributes:
            #   type: module

        # optional if youre using css
        stylesheets:
          'Sandstorm.ContentWorkflow':
            resource: 'resource://Sandstorm.ContentWorkflow/Public/built/ContentModule.css'
      changes:
        types:
          'Sandstorm.ContentWorkflow:HandleCommand': Sandstorm\ContentWorkflow\Ui\Changes\HandleCommand
  Flow:
    object:
      includeClasses:
        'Sandstorm.ContentWorkflow':
          - '^(?!.*Domain).*$'
